name: Python IDB
on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.13']

    name: Python ${{ matrix.python-version }} at ${{ matrix.os }}
    steps:
    - name: Checkout python-evtx with submodules
      uses: actions/checkout@v2

    - uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.2"
        python-version: ${{ matrix.python-version }}

    - name: install
      run: uv sync --dev

    - uses: extractions/setup-just@v2
      with:
        just-version: 1.5.0

    - name: lint
      run: just lint

    - name: test
      run: just test
